name: The WebKitGTK Project
url: https://webkitgtk.org
exclude: ['README.md', 'generate-site', 'releases', 'webkit-release', 'planet', 'generate-planet', 'generate-security-advisory', 'reference', 'cvedata']

stable-release-version: 2.24.3
unstable-release-version: 2.25.4
